### ISSUE TITLE
Eroare PaymentAbstract.

### ISSUE THREAD

**Issue by Siteq** [mobilpay/composer#1]
Am implementat versiunea care se instaleaza prin composer. Rezultatul este ca paymentRequest functioneaza perfect, genereaza EnvKey si Data, ne redirectioneaza catre link-ul de plati, plata se efectueaza, dar problema apare la confirmarea ei pe returnURL, din cauza unei erori care apare in clasa PaymentAbstract.

Dupa efectuarea unui composer update, nu a avut loc nicio actualizare (apare mesajul: _nothing to update_), insa am observat ultimele commit-uri facute de dumneavoastra pe github si am facut aceleasi modificari in fisierele corespunzatoare. Ulterior, am facut un test si am primit eroarea urmatoare:

Uncaught exception: 'TypeError' with message 'Argument 1 passed to Netopia\Payment\Request\PaymentAbstract::_factoryFromXml() must be an instance of Netopia\Payment\Request\DOMDocument, instance of DOMDocument given, called in /home/.../.../vendor/netopia/payment/src/Request/PaymentAbstract.php on line 135'
Stack trace: #0 /home/.../.../vendor/netopia/payment/src/Request/PaymentAbstract.php(135): Netopia\Payment\Request\PaymentAbstract::_factoryFromXml(Object(DOMDocument))

Asteptam o solutie din partea dumneavoastra pentru a continua testele.
Va multumim.

**Comment by gretriever37** [comment]
Make sure if you have the necessary extensions in your server
Such as :  Dom,  soap, Iblxml, SimpleXML,  xml, xmlreader,  xmlwriter,  ...

**Comment by navid59** [comment]
în primul rând multumim pentru ca ati folosit acest composer.

Probabil pentru ca ai schimbat manual sa poate ca lipseşte cel putin o modificare la codul Dvs.
Deci, este mai bine să ștergeți acest pachet și să îl instalați din nou, cu Composer.

vă rog, atenție la linia # 187 din PaymentAbestrac.php
de fapt, eroarea dvs. este de la linia #187 și nu de la linia #135
**DOMDocument** trebuie cu un `"\"` înainte

În general, oriunde există **DOMDocument**, **DOMNode**, **Exception**, **stdClass** ar trebui să fie cu un `"\"` înainte

Va Multumesc
