### ISSUE TITLE
Documentation regarding sending the POST details

### ISSUE THREAD

**Issue by SebastianBotez** [mobilpay/composer#12]
Hello guys.
Thank you for this Laravel implementation, is very useful. You did a great job as always.
I want to point out a recommendation that can be added in doc.

In the last step, we should send the data, env_key etc with POST.
When you read it, our first thought is to send it with HTTP request or CURL. When we do this, we get a error message that says: Unable to decrypt data or smth like that.

Solution:
Create a view with a form like this and send the data to the view.

```
resources/views: payment-form-blade.php
<form id="paymentForm" action="{{ $paymentData['url'] }}" method="POST">
    <input type="hidden" name="env_key" value="{{ $paymentData['env_key'] }}">
    <input type="hidden" name="data" value="{{ $paymentData['data'] }}">
    <input type="hidden" name="cipher" value="{{ $paymentData['cipher'] }}">
    <input type="hidden" name="iv" value="{{ $paymentData['iv'] }}">
</form>

<script>
    document.getElementById('paymentForm').submit();
</script>
```

After doing this, all is working fine.

Keep up the good work.

**Comment by navid59** [comment]
First of all, thank you for your recommendation.
We are glad to hear that the composer is helpful.

The README file has been updated with a UI example.
