### ISSUE TITLE
Update classes at least for address

### ISSUE THREAD

**Issue by razvanioan** [mobilpay/composer#2]
Although this repository for `composer` and the one for `OpenCart` for example are both tagged as version 1.0 there are differences at least for Address class, where the one for OpenCart has support for other fields like country, county, city, zip, bank, iban, etc

Can the composer repository be updated & maintained as well ?

**Comment by navid59** [comment]
Thank you for mention this point.
We will update the Composer, soon.

Regarding the Version tags, each repository are independent.
And the Version will be changes base on the updates on each repository .

**Comment by razvanioan** [comment]
I hope you'll update it soon otherwise I'll have to try / switch to manual update from the other repositories in order to support company customer type.

For instance with this current composer version, even if I set the billing type as `company` in my request, in the IPN message returned from you it's reported as `person` ...

**Comment by navid59** [comment]
The Address in current API is suppose to receive a full address, 
so Country , City , ... need to be added to the address as a single String.

**Comment by razvanioan** [comment]
Yeah, I've seen the update ... so I'll skip it as I was already doing this myself with the old version ...
