### ISSUE TITLE
Incompatibilitate php8

### ISSUE THREAD

**Issue by appm-io** [mobilpay/composer#3]
ArgumentCountError Object
                        (
                            [message:protected] => openssl_seal() expects at least 5 arguments, 4 given
                            [string:Error:private] => 
                            [code:protected] => 0
                            [file:protected] => /vendor/netopia/payment/src/Request/PaymentAbstract.php
                            [line:protected] => 325
                            [trace:Error:private] => Array

**Comment by navid59** [comment]
Thank you for letting us know
please, update from Git and let us know

**Comment by appm-io** [comment]
It's ok now. Thank you.
