### ISSUE TITLE
openssl_seal uses RC4 cipher_algo witch is insecure

### ISSUE THREAD

**Issue by costiiordan** [mobilpay/composer#6]
Mobilpay\Payment\Request\RequestAbstract.php uses openssl_seal with RC4 cipher_algo
Php docs states the following: Caution The default value ('RC4') is considered insecure. It is strongly recommended to explicitly specify a secure cipher method.
See docs here: https://www.php.net/manual/en/function.openssl-seal.php

**Comment by navid59** [comment]
For legacy reasons - there are quite a lot of companies that still use old keys/modules - we need to keep the RC4 compatibility in place. But since the payloads anyway come over HTTPS - which uses - TLS1.2 and above, there is absolutely no risk involved
