### ISSUE TITLE
PHP8 openssl_open() needs cipher_algo param

### ISSUE THREAD

**Issue by costiiordan** [mobilpay/composer#7]
https://github.com/mobilpay/composer/blob/85e31b738a7cf1f2ec18c56e3cac41f421f07775/src/Request/PaymentAbstract.php#L178

see docs: https://www.php.net/manual/en/function.openssl-open.php

**Comment by navid59** [comment]
It's already fixed and pushed on Git, days ago
The package is updated now too.
Please, update your app.

Let us know if you have any other problem, including the Framework & Version what you using.
