### ISSUE TITLE
About Split Payments 

### ISSUE THREAD

**Issue by sorinspanu** [mobilpay/composer#8]
Hello,
It is possible to extend this library in order to use Mobilpay Split Payments?

**Comment by navid59** [comment]
Thank you for the suggestion.
Split payments in composer is on our to do list and will be prioritised based on demand.

**Comment by leshobster** [comment]
+1, it would be helpful to have split payments included in this library.

**Comment by navid59** [comment]
Hello, Thank you for the interest and recommendation .
Inform form know this composer work for Split Payment as well
